#!/usr/bin/env bash
source "$(dirname "$0")/lib.sh"
L=$PWD/plugins/core/scripts/design-lint.sh
T=$(mktemp -d); mkdir -p "$T/src/app"
echo ':root{--brand:#123456}' > "$T/src/app/globals.css"
echo '<div className="text-sm bg-card">ok</div>' > "$T/src/ok.tsx"
assert_exit 0 bash "$L" "$T/src/app/globals.css" "$T/src/ok.tsx"
echo '<div style={{color:"#ff0000"}}>' > "$T/src/bad1.tsx"
assert_exit 1 bash "$L" "$T/src/bad1.tsx"
echo '<p className="text-[13px] mt-[7px]">' > "$T/src/bad2.tsx"
assert_exit 1 bash "$L" "$T/src/bad2.tsx"
assert_contains "$(bash "$L" "$T/src/bad2.tsx" 2>&1)" 'text-\[13px\]' "reports the offending token"
echo '<div className="data-[state=checked]:bg-primary grid-cols-[repeat(3,1fr)]">' > "$T/src/variant.tsx"
assert_exit 0 bash "$L" "$T/src/variant.tsx"
echo '<div className="text-[13px]">' > "$T/src/bad3.tsx"
assert_exit 1 bash "$L" "$T/src/bad3.tsx"
echo '<div className="bg-[var(--surface)] text-[13px]">' > "$T/src/mixed.tsx"
assert_exit 1 bash "$L" "$T/src/mixed.tsx"
echo '<div className="bg-[var(--surface)] w-[--sidebar-w]">' > "$T/src/tokref.tsx"
assert_exit 0 bash "$L" "$T/src/tokref.tsx"
echo 'const colors = ["#ff0000", "var(--brand)"];' > "$T/src/arr.tsx"
assert_exit 1 bash "$L" "$T/src/arr.tsx"
rm -rf "$T"; finish
